### ISSUE TITLE
Add option to disable video

### ISSUE THREAD

**Issue by sta1r** [bigbite/wp-cypress#139]
**Is your feature request related to a problem? Please describe.**
I'm running wp-cypress tests in a CI pipeline, where I have no access to videos recorded from a test run. 

**Describe the solution you'd like**
A switch on cypress.json config to set `video` to `false` per the [Cypress config options](https://docs.cypress.io/guides/references/legacy-configuration#Videos).

**Comment by ampersarnie** [comment]
Hey thanks for reporting the issue. You can still disable video by adding it to your `Cypress.json` config. For example your config may be:

```json
{
  "video": false,
  "wp": {
    "version": ["5.5"],
    "plugins": ["./path/to/plugin", "./another/path/to/plugin"],
    "themes": ["./path/to/theme"],
    "muPlugins": {
       "vip": true
    }
  }
}
```

Any Cypress config should work as expected, let us know if you come across any further issues.
