### ISSUE TITLE
Add Tests

### ISSUE THREAD

**Issue by liamdefty** [bigbite/wp-cypress#30]
**Is your feature request related to a problem? Please describe.**
Now that the api is becoming a little more stable, it would be good to add unit tests and integration tests. 

**Describe the solution you'd like**
Utility functions and modules are unit tested. Core features are integraton tested. We can use Cypress to achieve this - inception.

**Comment by ampersarnie** [comment]
Started in #85 but will flesh out required tests and additional information in a dedicated issue.
