### ISSUE TITLE
README badges not found

### ISSUE THREAD

**Issue by strarsis** [bigbite/wp-cypress#57]
**Describe the bug**
The badges (npm and license) are not found in the README of this repository.

**To Reproduce**
1. Visit the README of this repository.
Notice the error placeholders for the two badges.

**Expected behavior**
Badge images should load.

**Comment by liamdefty** [comment]
Seems to be working ok for me, perhaps NPM was having a bad day? 😆 

![image](https://user-images.githubusercontent.com/15612152/111918690-3b47b680-8a7e-11eb-8227-4340145ee17b.png)

Closing as unable to re-produce
