### ISSUE TITLE
Expose DB port

### ISSUE THREAD

**Issue by danrhjones** [bigbite/wp-cypress#58]
For a project I have had to frequently inspect the database to help me recreate certain posts.

It is is easy enough to go on to the MariaDB docker container and use the command line to do this, however, each time I rebuild the container, I lose the connection, and my terminal just isn't wide enough to easily view the outputted data.

I have manually added an exposed port in to `docker-compose.ejs` and rerun the container, and now I am able to inspect the database in a nice database IDE.

So it would be good to have the option to have the db port exposed, either permanently, or to have it configured.

**Comment by liamdefty** [comment]
Hey @danrhjones 

This sounds like a good idea and can definitely see the benefit 👏🏽 

> I have manually added an exposed port in to docker-compose.ejs

Since you've already looked at this, would you like to create a PR with this change? No worries if not, I'm hoping to spend some time this week on the next release so can squeeze it in with that

**Comment by danrhjones** [comment]
https://github.com/bigbite/wp-cypress/pull/60

I haven't updated the wiki as I am not sure how to do that

**Comment by liamdefty** [comment]
@danrhjones 💥

Thanks for this! I'll take a look this week
