### ISSUE TITLE
Wiki - Typo - "programatically" instead of "programmatically"

### ISSUE THREAD

**Issue by over-engineer** [bigbite/wp-cypress#97]
I believe there's a small typo in the wiki, at the [Authentification](https://github.com/bigbite/wp-cypress/wiki/Auth-and-Users#authentification) section, under [Auth and Users](https://github.com/bigbite/wp-cypress/wiki/Auth-and-Users). It says "programatically" instead of "programmatically" (two `m`s).

**Comment by PaulREnglish** [comment]
I've made the necessary changes: https://github.com/bigbite/wp-cypress/wiki/Auth-and-Users#authentification
