### ISSUE TITLE
Wiki - Missing options from the configuration schema

### ISSUE THREAD

**Issue by over-engineer** [bigbite/wp-cypress#98]
The [Configuration Options](https://github.com/bigbite/wp-cypress/wiki/Configuration-Options) table, which contains the full reference of available configuration options, is missing the `themes` and `plugins` options.

These are the missing rows:

| Property  | Required | Default |
| --------- | -------- | ------- |
| `themes`  | Optional | `null`  |
| `plugins` | Optional | `null`  |

And their sections below:

themes
---

- Type: `string[]`
- Example: `["./path/to/theme"]`

plugins
---

- Type: `string[]`
- Example: `["./path/to/plugin", "./another/path/to/plugin"]`

**Comment by PaulREnglish** [comment]
I've made the necessary changes: https://github.com/bigbite/wp-cypress/wiki/Configuration-Options.
Do you want to have a quick check @ampersarnie?
